### ISSUE TITLE
The extension doesn't work in VSCode 1.59

### ISSUE THREAD

**Issue by sanek-z** [formulahendry/vscode-mysql#174]
Hello.

The extension has broken after updating VSC to the latest version 1.59.

> Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043

If you try to execute some operations of the extension you will get:
![image](https://user-images.githubusercontent.com/88551886/128591776-3a1157b4-6a6d-46c9-8531-f1562e580686.png)

> Command 'MySQL: Add Connection' resulted in an error (command 'mysql.addConnection' not found)

**Comment by Kinvy66** [comment]
I have the same issue，and my vscode‘s   version is  1.59.0

**Comment by tom472** [comment]
Additional info that may be useful - 
In my instance I lost the list of any previous connections and have lost the ability to add any new ones.
Clicking on the `+` sign does not do anything and also does not produce any error(s).

VSC Details:

> Version: 1.59.0 (user setup)
> Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
> Date: 2021-08-04T23:13:12.822Z
> Electron: 13.1.7
> Chrome: 91.0.4472.124
> Node.js: 14.16.0
> V8: 9.1.269.36-electron.0
> OS: Windows_NT x64 10.0.18363

Extension Details:

> formulahendry.vscode-mysql  v0.4.1

**Comment by smraj-mani** [comment]
Add to this, below is the erro seen in the VSCode extension logs:

`[2021-08-12 16:39:09.336] [exthost] [error] Activating extension formulahendry.vscode-mysql failed due to an error:
[2021-08-12 16:39:09.336] [exthost] [error] Error: Cannot find module '/<user_home>/.vscode/extensions/formulahendry.vscode-mysql-0.4.1/node_modules/mysql/lib/Connection'
	at t (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:358851)
	at Object.patch (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:143340)
	at Module.require (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:39134)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/<user_home>/.vscode/extensions/formulahendry.vscode-mysql-0.4.1/out/common/utility.js:14:15)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at Module.require (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:38760)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/<user_home>/.vscode/extensions/formulahendry.vscode-mysql-0.4.1/out/common/appInsightsClient.js:5:19)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at Module.require (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:38760)
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:698)
	at Object.<anonymous> (/<user_home>/.vscode/extensions/formulahendry.vscode-mysql-0.4.1/out/extension.js:5:29)
	at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1315)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
	at Module.load (internal/modules/cjs/loader.js:982:32)
	at Module._load (internal/modules/cjs/loader.js:823:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.P._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at Module.require (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/microsoft-authentication/dist/extension.js:1:38760)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
	at v._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:26057)
	at v._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12603)
	at v._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11704)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
`
